
import {
    PeopleNumSetting,
    MeepoFormAddressEndSetting,
    MeepoFormAddressSetting,
    MeepoFormAddressStartSetting,
    MeepoFormBaojiaSetting,
    MeepoFormBtnSetting,
    MeepoFormFeeSetting,
    MeepoFormIdcardSetting,
    MeepoFormInputSetting,
    MeepoFormMobileSetting,
    MeepoFormMoneySetting,
    MeepoFormOrderSetting,
    MeepoFormPriceSetting,
    MeepoFormRealnameSetting,
    MeepoFormTagSetting,
    MeepoFormTextareaSetting,
    MeepoFormTijiSetting,
    MeepoFormTimeEndSetting,
    MeepoFormTimeSetting,
    MeepoFormTimeStartSetting,
    MeepoFormWeightSetting
} from './index';

export const forms_settings = [
    PeopleNumSetting,
    MeepoFormAddressEndSetting,
    MeepoFormAddressSetting,
    MeepoFormAddressStartSetting,
    MeepoFormBaojiaSetting,
    MeepoFormBtnSetting,
    MeepoFormFeeSetting,
    MeepoFormIdcardSetting,
    MeepoFormInputSetting,
    MeepoFormMobileSetting,
    MeepoFormMoneySetting,
    MeepoFormOrderSetting,
    MeepoFormPriceSetting,
    MeepoFormRealnameSetting,
    MeepoFormTagSetting,
    MeepoFormTextareaSetting,
    MeepoFormTijiSetting,
    MeepoFormTimeEndSetting,
    MeepoFormTimeSetting,
    MeepoFormTimeStartSetting,
    MeepoFormWeightSetting
];
export const forms_setting_map = {
    'people-num': PeopleNumSetting,
    'meepo-form-address-end': MeepoFormAddressEndSetting,
    'meepo-form-address':MeepoFormAddressSetting,
    'meepo-form-address-start':MeepoFormAddressStartSetting,
    'meepo-form-baojia':MeepoFormBaojiaSetting,
    'meepo-form-btn':MeepoFormBtnSetting,
    'meepo-form-fee':MeepoFormFeeSetting,
    'meepo-form-idcard':MeepoFormIdcardSetting,
    'meepo-form-input':MeepoFormInputSetting,
    'meepo-form-mobile':MeepoFormMobileSetting,
    'meepo-form-money':MeepoFormMoneySetting,
    'meepo-form-order':MeepoFormOrderSetting,
    'meepo-form-pirce':MeepoFormPriceSetting,
    'meepo-form-realname':MeepoFormRealnameSetting,
    'meepo-form-tag':MeepoFormTagSetting,
    'meepo-form-textarea':MeepoFormTextareaSetting,
    'meepo-form-tiji':MeepoFormTijiSetting,
    'meepo-form-time-end':MeepoFormTimeEndSetting,
    'meepo-form-time':MeepoFormTimeSetting,
    'meepo-form-time-start':MeepoFormTimeStartSetting,
    'meepo-form-weight':MeepoFormWeightSetting
};
