
import {
    PeopleNumView,
    MeepoFormAddressEndView,
    MeepoFormAddressView,
    MeepoFormAddressStartView,
    MeepoFormBaojiaView,
    MeepoFormBtnView,
    MeepoFormFeeView,
    MeepoFormIdcardView,
    MeepoFormInputView,
    MeepoFormMobileView,
    MeepoFormMoneyView,
    MeepoFormOrderView,
    MeepoFormPriceView,
    MeepoFormRealnameView,
    MeepoFormTagView,
    MeepoFormTextareaView,
    MeepoFormTijiView,
    MeepoFormTimeEndView,
    MeepoFormTimeView,
    MeepoFormTimeStartView,
    MeepoFormWeightView,
} from './index';

export const forms_views = [
    PeopleNumView,
    MeepoFormAddressEndView,
    MeepoFormAddressView,
    MeepoFormAddressStartView,
    MeepoFormBaojiaView,
    MeepoFormBtnView,
    MeepoFormFeeView,
    MeepoFormInputView,
    MeepoFormMobileView,
    MeepoFormMoneyView,
    MeepoFormOrderView,
    MeepoFormPriceView,
    MeepoFormRealnameView,
    MeepoFormTagView,
    MeepoFormTextareaView,
    MeepoFormTijiView,
    MeepoFormTimeEndView,
    MeepoFormTimeView,
    MeepoFormTimeStartView,
    MeepoFormWeightView,
    MeepoFormIdcardView
];
export const forms_view_map = {
    'people-num': PeopleNumView,
    'meepo-form-address-end': MeepoFormAddressEndView,
    'meepo-form-address':MeepoFormAddressView,
    'meepo-form-address-start':MeepoFormAddressStartView,
    'meepo-form-baojia':MeepoFormBaojiaView,
    'meepo-form-btn':MeepoFormBtnView,
    'meepo-form-fee':MeepoFormFeeView,
    'meepo-form-idcard':MeepoFormIdcardView,
    'meepo-form-input':MeepoFormInputView,
    'meepo-form-mobile':MeepoFormMobileView,
    'meepo-form-money':MeepoFormMoneyView,
    'meepo-form-order':MeepoFormOrderView,
    'meepo-form-pirce':MeepoFormPriceView,
    'meepo-form-realname':MeepoFormRealnameView,
    'meepo-form-tag':MeepoFormTagView,
    'meepo-form-textarea':MeepoFormTextareaView,
    'meepo-form-tiji':MeepoFormTijiView,
    'meepo-form-time-end':MeepoFormTimeEndView,
    'meepo-form-time':MeepoFormTimeView,
    'meepo-form-time-start':MeepoFormTimeStartView,
    'meepo-form-weight':MeepoFormWeightView,
};
